### PR TITLE
A look into hosting on Shuttle.rs

### LINKED ISSUE #13: Hosting
We should look into hosting (preferably free hosting with CI/CD support)
We could use [Shuttle](https://www.shuttle.rs/pricing) as we fit nicely in their free tier, but there are loads of other platforms we can look into.

### PR DESCRIPTION
**Pull request by SvartaHjarta**
Will close #13 ~~at some point.~~

- [x] Deploying works
- [x] Automate deployments using Ci/Cd

### CODE REVIEW

**Comment by SvartaHjarta** [comment]
Effectively just the example off the Shuttle-rs Git repo, just enough to get it up and running.

use `cargo shuttle run` to test changes localy
use `cargo shuttle deploy` to deploy

**Comment by SvartaHjarta** [comment]
I'm not sure how to fix this but Shuttle terminates the service if it idles for more than 30 minutes
Perhaps we can just print hello world every 20 minutes.
```
Project "rubot" is stopped
Idle minutes: 30
```

**Comment by SvartaHjarta** [comment]
> I'm not sure how to fix this but Shuttle terminates the service if it idles for more than 30 minutes Perhaps we can just print hello world every 20 minutes.
> 
> ```
> Project "rubot" is stopped
> Idle minutes: 30
> ```

Shuttle.rs allows one to set idle timeout, setting it to zero solves this issue.

**Comment by SvartaHjarta** [comment]
When this is merged RUbot should deploy to Shuttle.

Running the porject should now be run with `cargo shuttle run` for testing locally.

**Review by samuelhafsteins — APPROVED** [review]
LGTM

**Pull request merged**
