### PR TITLE
Initial draft for ci/cd

### LINKED ISSUE #19: Add pipelines
- [ ] Building
- [ ] Testing
- [ ] Format
Check on caching for cargo to speed up actions.

### PR DESCRIPTION
**Pull request by SvartaHjarta**
This workflow runs the following commands in order.

- cargo build --verbose
- cargo test --verbose
- cargo fmt --verbose --check

Closes #19 

Build takes quite some time, should look into caching.

### CODE REVIEW

**Review by samuelhafsteins — APPROVED** [review]
LGTM

**Comment by SvartaHjarta** [comment]
> LGTM, now you just gotta pass the format checker

Easy pass, think I'll work on caching before merging.

**Comment by samuelhafsteins** [comment]
> > LGTM, now you just gotta pass the format checker
> 
> Easy pass, think I'll work on caching before merging. Maybe it's better left as a separate PR?

I think it's all good to add it with this one

**Comment by SvartaHjarta** [comment]
Caching is now implemented, I'm unsure if the keys are setup properly but I think we will figure that out as we go.

**Pull request merged**
